version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M@sterk3y
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - impacta_infra

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - impacta_infra

  web:
    image: nginx
    volumes:
      - templates:/etc/nginx/templates
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
    networks:
      - impacta_infra

networks:
  impacta_infra:
    driver: bridge

volumes:
  database:
  templates:
